from django.conf.urls import url
from django.contrib import admin
from jk import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^page=(\d*)$', views.pageindex, name='pageindex'),
    url(r'^sport/$', views.SportG, name='sport'),
    url(r'^sport/page=(\d*)$', views.Sportpage, name='sportpage'),
    url(r'^sport/.*-(\d+)$', views.Sportw, name='sportw'),
    url(r'^idees/$', views.IdeesG, name='idees'),
    url(r'^idees/page=(\d*)$', views.Ideespage, name='ideespage'),
    url(r'^idees/.*-(\d+)$', views.Ideesw, name='ideesw'),
    url(r'^societe/$', views.SocieteG, name='societe'),
    url(r'^societe/page=(\d*)$', views.Societepage, name='societepage'),
    url(r'^societe/.*-(\d+)$', views.Societew, name='societew'),
    url(r'^culture/$', views.CultureG, name='culture'),
    url(r'^culture/page=(\d*)$', views.Culturepage, name='culturepage'),
    url(r'^culture/.*-(\d+)$', views.Culturew, name='culturew'),
    url(r'^economie/$', views.EconomieG, name='economie'),
    url(r'^economie/page=(\d*)$', views.Economiepage, name='economiepage'),
    url(r'^economie/.*-(\d+)$', views.Economiew, name='economiew'),
    url(r'^editorial/$', views.EditorialG, name='editorial'),
    url(r'^editorial/page=(\d*)$', views.Editorialpage, name='editorialpage'),
    url(r'^editorial/.*-(\d+)$', views.Editorialw, name='editorialw'),
    url(r'^national/$', views.NationalG, name='national'),
    url(r'^national/page=(\d*)$', views.Nationalpage, name='nationalpage'),
    url(r'^national/.*-(\d+)$', views.Nationalw, name='nationalew'),
    url(r'^sante/$', views.SanteG, name='sante'),
    url(r'^sante/page=(\d*)$', views.Santepage, name='santepage'),
    url(r'^sante/.*-(\d+)$', views.Santew, name='santew'),
    url(r'^ticketmag/$', views.TicketmagG, name='ticketmag'),
    url(r'^ticketmag/page=(\d*)$', views.Ticketmagpage, name='ticketmag'),
    url(r'^ticketmag/.*-(\d+)$', views.Ticketmagw, name='ticketmag'),
    url(r'^en/$', views.indexen, name='indexen'),
    url(r'^en/page=(\d*)$', views.pageindexen, name='pageindexen'),
    url(r'^en/news/$', views.Newsen, name='newsen'),
    url(r'^en/news/page=(\d*)$', views.Newsenpage, name='newsenpage'),
    url(r'^en/news/.*-(\d+)$', views.Newsenw, name='newsenw'),
    url(r'^en/politics/$', views.Politicsen, name='politicsen'),
    url(r'^en/politics/page=(\d*)$', views.Politicsenpage, name='politicsenpage'),
    url(r'^en/politics/.*-(\d+)$', views.Politicsenw, name='politicsenw'),
    url(r'^en/business/$', views.Businessen, name='businessen'),
    url(r'^en/business/page=(\d*)$', views.Businessenpage, name='businessenpage'),
    url(r'^en/business/.*-(\d+)$', views.Businessenw, name='businessenw'),
    url(r'^en/opinion/$', views.Opinionen, name='opinionen'),
    url(r'^en/opinion/page=(\d*)$', views.Opinionenpage, name='opinionenpage'),
    url(r'^en/opinion/.*-(\d+)$', views.Opinionenw, name='opinionenw'),
    url(r'^en/tech/$', views.Techen, name='techen'),
    url(r'^en/tech/page=(\d*)$', views.Techenpage, name='techenpage'),
    url(r'^en/tech/.*-(\d+)$', views.Techenw, name='techenw'),
    url(r'^en/science/$', views.Scienceen, name='scienceen'),
    url(r'^en/science/page=(\d*)$', views.Scienceenpage, name='scienceenpage'),
    url(r'^en/science/.*-(\d+)$', views.Scienceenw, name='scienceenw'),
    url(r'^en/health/$', views.Healthen, name='healthen'),
    url(r'^en/health/page=(\d*)$', views.Healthenpage, name='healthenpage'),
    url(r'^en/health/.*-(\d+)$', views.Healthenw, name='healthenw'),

]
